In [11]:
import geopandas as gpd
from pyproj import Transformer
import pandas as pd 
import warnings
warnings.filterwarnings('ignore')

# first transform everything to standard coordinates

In [5]:
# INDOOR
# Load the CSV file into a GeoDataFrame
gdf = gpd.read_file('../data/Galv_Bins_July_Version/indoor.csv')

# Define the source and target coordinate systems
source_crs = 'EPSG:3857'  # Web Mercator (WGS_1984_Web_Mercator_Auxiliary_Sphere)
target_crs = 'EPSG:4326'  # WGS84 (decimal degrees)

# Create a transformer to handle the coordinate conversion
transformer = Transformer.from_crs(source_crs, target_crs, always_xy=True)

# Apply the coordinate transformation to all points
gdf['longitude'], gdf['latitude'] = transformer.transform(gdf['x'].values, gdf['y'].values)

# Now, your DataFrame contains the points in latitude-longitude format (WGS84 decimal degrees)
gdf.head()

,OBJECTID,Title,x,y,geometry,longitude,latitude
0,1,Point,-10547593.340226736,3416411.0042788377,None,-94.750643,29.319787
1,2,Point,-10555119.18421213,3415916.9732835186,None,-94.818249,29.315917
2,3,Point,-10553039.426632557,3414408.2237252686,None,-94.799566,29.304099
3,4,Point,-10552959.12669782,3414428.2497228202,None,-94.798845,29.304256
4,5,Point,-10552963.705734883,3414389.380392919,None,-94.798886,29.303951

In [6]:
# OUTDOOR
# Load the CSV file into a GeoDataFrame
gdf2 = gpd.read_file('../data/Galv_Bins_July_Version/outdoor.csv')

# Define the source and target coordinate systems
source_crs = 'EPSG:3857'  # Web Mercator (WGS_1984_Web_Mercator_Auxiliary_Sphere)
target_crs = 'EPSG:4326'  # WGS84 (decimal degrees)

# Create a transformer to handle the coordinate conversion
transformer = Transformer.from_crs(source_crs, target_crs, always_xy=True)

# Apply the coordinate transformation to all points
gdf2['longitude'], gdf2['latitude'] = transformer.transform(gdf2['x'].values, gdf2['y'].values)

# Now, your DataFrame contains the points in latitude-longitude format (WGS84 decimal degrees)
gdf2.head()

,OBJECTID,Title,x,y,geometry,longitude,latitude
0,1,Point,-10546257.038316488,3418024.8012757357,None,-94.738639,29.332426
1,2,Point,-10546821.321241608,3417229.69569367,None,-94.743708,29.326199
2,3,Point,-10546387.294775823,3417600.8519572346,None,-94.739809,29.329106
3,4,Point,-10545750.661665484,3417921.4172091587,None,-94.734090,29.331616
4,6,Point,-10548708.994864443,3415509.825234467,None,-94.760665,29.312728

In [18]:
# COMBINE INDOOR AND OUTDOOR INTO A SINGLE GEODATAFRAME WITH "LONGITUDE" AND "LATITUDE" COLUMNS ONLY
# CLEAN UP AND GIVE EACH ROW A UNIQUE OBJECTID

data = gdf.append(gdf2, ignore_index=True)
data = data[['OBJECTID', 'longitude', 'latitude']]
data['OBJECTID'][:30] = [i for i in range(1001, 1031)]
data['OBJECTID'][30:] = [i for i in range(2001, 2129)]
data.head()

  OBJECTID  longitude   latitude
0     1001 -94.750643  29.319787
1     1002 -94.818249  29.315917
2     1003 -94.799566  29.304099
3     1004 -94.798845  29.304256
4     1005 -94.798886  29.303951